
package introsde.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HealthServiceImplementationService", targetNamespace = "http://ws.introsde/", wsdlLocation = "http://localhost:6901/ws/health?wsdl")
public class HealthServiceImplementationService
    extends Service
{

    private final static URL HEALTHSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException HEALTHSERVICEIMPLEMENTATIONSERVICE_EXCEPTION;
    private final static QName HEALTHSERVICEIMPLEMENTATIONSERVICE_QNAME = new QName("http://ws.introsde/", "HealthServiceImplementationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:6901/ws/health?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HEALTHSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION = url;
        HEALTHSERVICEIMPLEMENTATIONSERVICE_EXCEPTION = e;
    }

    public HealthServiceImplementationService() {
        super(__getWsdlLocation(), HEALTHSERVICEIMPLEMENTATIONSERVICE_QNAME);
    }

    public HealthServiceImplementationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HEALTHSERVICEIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public HealthServiceImplementationService(URL wsdlLocation) {
        super(wsdlLocation, HEALTHSERVICEIMPLEMENTATIONSERVICE_QNAME);
    }

    public HealthServiceImplementationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HEALTHSERVICEIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public HealthServiceImplementationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HealthServiceImplementationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HealthServiceInterface
     */
    @WebEndpoint(name = "HealthServiceImplementationPort")
    public HealthServiceInterface getHealthServiceImplementationPort() {
        return super.getPort(new QName("http://ws.introsde/", "HealthServiceImplementationPort"), HealthServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HealthServiceInterface
     */
    @WebEndpoint(name = "HealthServiceImplementationPort")
    public HealthServiceInterface getHealthServiceImplementationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.introsde/", "HealthServiceImplementationPort"), HealthServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HEALTHSERVICEIMPLEMENTATIONSERVICE_EXCEPTION!= null) {
            throw HEALTHSERVICEIMPLEMENTATIONSERVICE_EXCEPTION;
        }
        return HEALTHSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    }

}
