
package introsde.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HealthServiceInterface", targetNamespace = "http://ws.introsde/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HealthServiceInterface {


    /**
     * 
     * @param arg0
     * @return
     *     returns introsde.ws.Person
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readPerson", targetNamespace = "http://ws.introsde/", className = "introsde.ws.ReadPerson")
    @ResponseWrapper(localName = "readPersonResponse", targetNamespace = "http://ws.introsde/", className = "introsde.ws.ReadPersonResponse")
    @Action(input = "http://ws.introsde/HealthServiceInterface/readPersonRequest", output = "http://ws.introsde/HealthServiceInterface/readPersonResponse")
    public Person readPerson(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns introsde.ws.Person
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updatePerson", targetNamespace = "http://ws.introsde/", className = "introsde.ws.UpdatePerson")
    @ResponseWrapper(localName = "updatePersonResponse", targetNamespace = "http://ws.introsde/", className = "introsde.ws.UpdatePersonResponse")
    @Action(input = "http://ws.introsde/HealthServiceInterface/updatePersonRequest", output = "http://ws.introsde/HealthServiceInterface/updatePersonResponse")
    public Person updatePerson(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0);

    /**
     * 
     * @return
     *     returns java.util.List<introsde.ws.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readPersonList", targetNamespace = "http://ws.introsde/", className = "introsde.ws.ReadPersonList")
    @ResponseWrapper(localName = "readPersonListResponse", targetNamespace = "http://ws.introsde/", className = "introsde.ws.ReadPersonListResponse")
    @Action(input = "http://ws.introsde/HealthServiceInterface/readPersonListRequest", output = "http://ws.introsde/HealthServiceInterface/readPersonListResponse")
    public List<Person> readPersonList();

    /**
     * 
     * @param arg0
     * @return
     *     returns introsde.ws.Person
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createPerson", targetNamespace = "http://ws.introsde/", className = "introsde.ws.CreatePerson")
    @ResponseWrapper(localName = "createPersonResponse", targetNamespace = "http://ws.introsde/", className = "introsde.ws.CreatePersonResponse")
    @Action(input = "http://ws.introsde/HealthServiceInterface/createPersonRequest", output = "http://ws.introsde/HealthServiceInterface/createPersonResponse")
    public Person createPerson(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deletePerson", targetNamespace = "http://ws.introsde/", className = "introsde.ws.DeletePerson")
    @ResponseWrapper(localName = "deletePersonResponse", targetNamespace = "http://ws.introsde/", className = "introsde.ws.DeletePersonResponse")
    @Action(input = "http://ws.introsde/HealthServiceInterface/deletePersonRequest", output = "http://ws.introsde/HealthServiceInterface/deletePersonResponse")
    public void deletePerson(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<introsde.ws.Measure>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readPersonHistory", targetNamespace = "http://ws.introsde/", className = "introsde.ws.ReadPersonHistory")
    @ResponseWrapper(localName = "readPersonHistoryResponse", targetNamespace = "http://ws.introsde/", className = "introsde.ws.ReadPersonHistoryResponse")
    @Action(input = "http://ws.introsde/HealthServiceInterface/readPersonHistoryRequest", output = "http://ws.introsde/HealthServiceInterface/readPersonHistoryResponse")
    public List<Measure> readPersonHistory(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns java.util.List<introsde.ws.MeasureDefinition>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readMeasureTypes", targetNamespace = "http://ws.introsde/", className = "introsde.ws.ReadMeasureTypes")
    @ResponseWrapper(localName = "readMeasureTypesResponse", targetNamespace = "http://ws.introsde/", className = "introsde.ws.ReadMeasureTypesResponse")
    @Action(input = "http://ws.introsde/HealthServiceInterface/readMeasureTypesRequest", output = "http://ws.introsde/HealthServiceInterface/readMeasureTypesResponse")
    public List<MeasureDefinition> readMeasureTypes();

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns introsde.ws.Measure
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readPersonMeasure", targetNamespace = "http://ws.introsde/", className = "introsde.ws.ReadPersonMeasure")
    @ResponseWrapper(localName = "readPersonMeasureResponse", targetNamespace = "http://ws.introsde/", className = "introsde.ws.ReadPersonMeasureResponse")
    @Action(input = "http://ws.introsde/HealthServiceInterface/readPersonMeasureRequest", output = "http://ws.introsde/HealthServiceInterface/readPersonMeasureResponse")
    public Measure readPersonMeasure(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Long arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns introsde.ws.Measure
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "savePersonMeasure", targetNamespace = "http://ws.introsde/", className = "introsde.ws.SavePersonMeasure")
    @ResponseWrapper(localName = "savePersonMeasureResponse", targetNamespace = "http://ws.introsde/", className = "introsde.ws.SavePersonMeasureResponse")
    @Action(input = "http://ws.introsde/HealthServiceInterface/savePersonMeasureRequest", output = "http://ws.introsde/HealthServiceInterface/savePersonMeasureResponse")
    public Measure savePersonMeasure(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Measure arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns introsde.ws.Measure
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updatePersonMeasure", targetNamespace = "http://ws.introsde/", className = "introsde.ws.UpdatePersonMeasure")
    @ResponseWrapper(localName = "updatePersonMeasureResponse", targetNamespace = "http://ws.introsde/", className = "introsde.ws.UpdatePersonMeasureResponse")
    @Action(input = "http://ws.introsde/HealthServiceInterface/updatePersonMeasureRequest", output = "http://ws.introsde/HealthServiceInterface/updatePersonMeasureResponse")
    public Measure updatePersonMeasure(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Measure arg1);

}
